
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY .cmake/output)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG .cmake/output)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE .cmake/output)

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY .cmake/output)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG .cmake/output)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE .cmake/output)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY .cmake/output)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG .cmake/output)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE .cmake/output)
